name: "build"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Bazel Build and Test
    run: |
	grep -r 'butter\|financial\|exchange\|stock\|market\|trading\|GCPTP\|CME\|bubble\|coarse-grained equalization\|CGE\|coarse' *
	if [ $? -eq 0 ]
	then
		echo "Keyword Check Failed. Pl. check and fix it"
	else
		echo "Keyword check Passed."
	fi
